### ISSUE TITLE
False Language Prediction [SPB]

### ISSUE THREAD

**Issue by sudo-nautilus** [intellivoid/issues#10]
**Describe the bug**

The title says it all, anyway the language prediction is falsepositive. I think I'm not the only one who's experiencing the same thing [meckron also does](https://t.me/SpamProtectionSupport/50550)

**To Reproduce**
- Just request userinfo

**Expected behavior**
Based language prediction

**Screenshots**
[![based indeed](https://user-images.githubusercontent.com/78522210/144419289-4cb16430-3c04-4569-a689-a72f3ce47db0.jpg)](https://t.me/SpamProtectionSupport/53908)

**Additional context**
Tried talking English in groups where the bot's presence is found and it still shows that I speaks Welsh.

**Comment by Netkas** [comment]
Hi, thank you for reporting this issue. We'll try to increase the generalization size for language prediction in hopes that this will fix the issue. But realize that anything machine learning related is not going to be 100% accurate, there will be inconsistencies. 

However, knowing that; this should not affect your experience with the bot unless you have your selected language set to Automatic.

**Comment by sudo-nautilus** [comment]
> Hi, thank you for reporting this issue. We'll try to increase the generalization size for language prediction in hopes that this will fix the issue.

Oh cool

> But realize that anything machine learning related is not going to be 100% accurate, there will be inconsistencies.

Ah I see, that's true


> However, knowing that; this should not affect your experience with the bot unless you have your selected language set to Automatic.

Hmmm 

Anyway thank you for considering this.
