### ISSUE TITLE
Spam Protection Bot doesn't respond to /start in PM

### ISSUE THREAD

**Issue by the-blank-x** [intellivoid/issues#11]
**Describe the bug**
Basically the title, Spam Protection Bot doesn't respond to `/start` in PM.

**To Reproduce**
Send `/start` to https://t.me/SpamProtectionBot

**Expected behavior**
The bot gives a response

**Screenshots**
The bot responding to `/language` and `/whois` but not `/start`:
![](https://i.imgur.com/HIAy32A.png)

**Additional context**
The bot does respond to `/start help`

**Comment by Netkas** [comment]
Hi, thank you for opening this issue.

This issue has been corrected and should be fixed in the next update.
[ref:8b555f19c7b3ca4f5b817cd32fc25b41332556aa](https://github.com/intellivoid/SpamProtectionBot/commit/8b555f19c7b3ca4f5b817cd32fc25b41332556aa)
