### ISSUE TITLE
Servers return HTML respond when sending large files

### ISSUE THREAD

**Issue by ALiwoto** [intellivoid/issues#3]
## What's the bug?
Coffeehouse [NSFW Classification API](https://docs.intellivoid.net/coffeehouse/v1/nsfw/basics), returns a respond in HTML format if we try to send a large data as base64 (since servers are down, I can't remember the exact size).
This is the respond:
```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.17.8</center>
</body>
</html>
```

> I looked at documentations of NSFW Classification API in [here](https://docs.intellivoid.net/coffeehouse/v1/nsfw), servers are down, but I have a local version of it on my computer; it doesn't give users that much information how they should handle this error, or what's the limitations of the API (or maybe I didn't see it?)

<hr/>

## What is wrong with this?
If users send a large data to servers, they will most likely get a "__json parser error__", since we are expecting a json error from server.
We can solve this problem with checking the file size in our own wrappers, but it won't solve the real problem, since another users can use the API in another ways. 

Is there any way to solve this _from server-side_? Or it's not possible?

<hr/>

## How to reproduce the error?
Simply send a large image file to the servers and the respond will be this.

**Expected behavior**
A JSON respond with a specified error message and error code, something like this:
```json
{
  "success": false,
  "response_code": 400,
  "error": {
    "error_code": 12,
    "type": "CLIENT",
    "message": "The file type isn't supported for this method"
  }
}
```
<hr/>

## Which environment did I use?
 - Golang
 - Version 1.16
 - Full source code is available [here](https://github.com/Dank-del/Intellivoid.Coffeehouse-go/blob/master/coffeehouse/mediaProcessing/classificationNSFW/helpers.go)

**Comment by Netkas** [comment]
Are you sending the image data in a the URL or a post request body? I don't think the API server returns a json response if the url is too large, so that could easily be fixed. But even then image data should be sent in the post body and not the URL.

**Comment by ALiwoto** [comment]
> Are you sending the image data in a the URL or a post request body? I don't think the API server returns a json response if the url is too large, so that could easily be fixed. But even then image data should be sent in the post body and not the URL.

I should use it in request body??
But documentation says we have to use key-value pairs for it
like this:
```go
v.Set(imageKey, imgBase64)
v.Set(accessKeyKey, cf.GetKey())
v.Set(generalizationKey, gen)
v.Set(generalizationSizeKey, genSize)

v.Set(generalizationIdKey, genId)

resp, err := http.PostForm(endpointurl, v)
``` 

<hr/>

Actually, I tried to send base64 value directly in url before, like this:
`https://api_url.com/nsfw?image_key=image_value&access_key=access_value`
but it didn't work, because of this error from `http` package in golang:
`write tcp 10.320.16.243:40126->273.64.140.40:443: write: broken pipe`
So, I decided to use `url.Values` (from `net/url` package).
It worked perfectly for all of the pictures I tested (with a small size)

**Comment by Netkas** [comment]
From what I'm seeing in the code, correct me if I'm wrong; you are just appending GET parameters instead of putting the data in the request body

Please see https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST￼

**Comment by Netkas** [comment]
Additionally the json error you showed in your issue states of a unsupported file, the API only accepts PNG and JPEG file formats, can you share the file you are trying to use with the API?

**Comment by ALiwoto** [comment]
> From what I'm seeing in the code, correct me if I'm wrong; you are just appending GET parameters instead of putting the data in the request body
> 
> Please see [https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST￼](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST%EF%BF%BC)

`http.PostForm` uses `POST` method for sending HTTP requests.
Actually, I tried a lot of more functions, like `http.Post`, but they didn't work at all (the error was for `access_key` not being set)

I will try another methods again (after servers come back online, to see if they will work or not, maybe the problem was from me).

<hr/>

Again this problem can be prevented on client side by checking the file size before even converting it to the base64 (in some cases if you compare, yes, it may take a little bit more running time, but it's the best choice right now, since it can prevent from disaster)
Thanks again for checking this issue and responding!

**Comment by Netkas** [comment]
This issue will remaim opened until i can confirm if it’s indeed a server issue, because file limits should return a json error and not a html error from the web server

**Comment by AntiEngineer** [comment]
Hello there.

Thanks for bringing this into our attention.

Since I'm the person in charge regarding these topics, I may want to know, if possible, the exact size in bytes (or kilobytes) of the data you're passing to our endpoint.

The error you're facing is not an error from Intellivoid Services but rather our load balancer configuration dropping requests which pass a certain size threshold. 

This also means it never reached the target Vision systems in charge of processing this type of content.


Looking forward to hearing back from you.

**Comment by Netkas** [comment]
This issue should already be fixed long-after the server was moved.
