### ISSUE TITLE
Login using telegram prompt isnt working

### ISSUE THREAD

**Issue by Kyliekyler** [intellivoid/issues#8]
**Describe the bug**
Couldn't sign in using telegram prompt

**To Reproduce**
1. Go to 'coffeehouse.intellivoid.net'
2. Click on 'dashboard and login'
3. Sign in using 'telegram prompt'
4. Go to 'telegram.dog/IntellivoidBot'
5. Click on 'allow'
6. See error

**Expected behavior**
To login ofc.

**Device & environment (please complete the following information if applicable):**
 - Device: Smartphone
 - OS: Android 12
 - Browser: Chrome, Mozilla

**Comment by Netkas** [comment]
This seems to be an issue with the server-side configuration, please take a look at the logs when possible @Justasic

**Comment by Justasic** [comment]
This issue appears to be resolved. Please reopen this issue if you are unable to login again.
