### ISSUE TITLE
When spam detection action is set to kick, it should unban too

### ISSUE THREAD

**Issue by the-blank-x** [intellivoid/issues#9]
**Describe the bug**
When spam detection action is set to kick, it bans for one minute but doesn't unban

**To Reproduce**
1. Run /settings in a chat
2. Click on Spam Detection
3. Cycle through the detecion action until you get to Delete & Kick Offender
4. Send spam from a non-admin account

**Expected behavior**
The offender is banned and unbanned immediately

**Screenshots**
![Spam Protection Bot deleting spam and banning the offender but not unbanning](https://user-images.githubusercontent.com/45762106/141276520-beb52374-b021-494d-93d8-251b7874fa6d.png)

**Comment by Netkas** [comment]
Thanks, will correct this in the next release.

**Comment by Netkas** [comment]
The issue has been resolved in v2.0.4.3, waiting for changes to apply to the server.

**Comment by Justasic** [comment]
Production has been updated with these changes, new behavior should now be available.
